# Generated by Django 4.2 on 2023-08-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do opcional')),
                ('valor', models.FloatField(default=0, verbose_name='Valor do opcional')),
            ],
        ),
        migrations.AddField(
            model_name='atrativo',
            name='opcionais',
            field=models.ManyToManyField(blank=True, to='elias.opcionais'),
        ),
    ]
