# Generated by Django 4.2 on 2023-08-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elias', '0002_opcionais_atrativo_opcionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='capa',
            field=models.FileField(blank=True, null=True, upload_to='static/imagens/', verbose_name='Imagem de Capa'),
        ),
    ]
