# Generated by Django 4.2 on 2023-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elias', '0003_experiencia_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='descricao',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Nome da Experiência'),
        ),
    ]
