# Generated by Django 5.0.7 on 2024-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elias', '0004_experiencia_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='descricao',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Descrição da Experiência'),
        ),
    ]
