# Generated by Django 5.0.7 on 2024-07-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elias', '0005_alter_experiencia_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do roteiro')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='static/imagens/', verbose_name='Imagem com Atrativos')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destacar na Página Inicial')),
                ('dias', models.IntegerField(default=0, verbose_name='Quantidade de Dias')),
                ('noites', models.IntegerField(default=0, verbose_name='Quantidade de Noites')),
            ],
            options={
                'verbose_name': 'ROTEIRO',
                'verbose_name_plural': 'ROTEIROS',
            },
        ),
    ]
