# Generated by Django 5.0.7 on 2024-07-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elias', '0006_roteiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='destacar',
            field=models.BooleanField(default=False, verbose_name='Destacar na página Inicial'),
        ),
    ]
